### ISSUE TITLE
invalid username erroe everytime

### ISSUE THREAD

**Issue by Bishalpchhetri** [saman0i0/Portfolio-Management-System#10]
I think there are errors in codes. please remove those errors
![Screenshot (73)](https://user-images.githubusercontent.com/82128769/118272051-c757e680-b4e1-11eb-8f5d-230aa5639a97.png)

**Comment by karuna502** [comment]
![image](https://user-images.githubusercontent.com/81338971/118350928-d2aa2100-b578-11eb-8c38-7b299021688a.png)
done
