### ISSUE TITLE
backend problem

### ISSUE THREAD

**Issue by Bishalpchhetri** [saman0i0/Portfolio-Management-System#12]
Im not being able to submit the data please manage this.

**Comment by karuna502** [comment]
![image](https://user-images.githubusercontent.com/81338971/118359649-2aaa4d00-b5a4-11eb-88d2-c423f5271b47.png)
It works
![Uploading save data fromregistration.PNG…]()

**Comment by karuna502** [comment]
![Uploading save data fromregistration.PNG…]()
