### ISSUE TITLE
unnecessary items

### ISSUE THREAD

**Issue by Bishalpchhetri** [saman0i0/Portfolio-Management-System#14]
please remove these mentioned items and make a simple design for logging out of system
![185269379_284255420020014_5651114614888862854_n](https://user-images.githubusercontent.com/82128769/118278635-ec505780-b4e9-11eb-9dda-91b27a7b31e3.png)

**Comment by VishalDip** [comment]
![0-02-03-b73cefab565043582ce06b756743cabd81d79af771c8252b41b6ecfb048909f5_29141b6f](https://user-images.githubusercontent.com/81339121/118393659-ea100980-b65f-11eb-96ae-11efc6c1a621.jpg)
I have changed the user icon dropdown and made a logout button instead of it.
