### ISSUE TITLE
unmattched icon

### ISSUE THREAD

**Issue by Bishalpchhetri** [saman0i0/Portfolio-Management-System#15]
please remove this item
![186503194_1415789198760144_2209671132178987278_n](https://user-images.githubusercontent.com/82128769/118279073-6b459000-b4ea-11eb-9b83-fac2f2fe324b.png)

**Comment by urushaudas** [comment]
![Screenshot (365)](https://user-images.githubusercontent.com/81338910/118313987-3863c200-b513-11eb-8618-c626700edd0e.png)

**Comment by urushaudas** [comment]
This issue is already fixed.
![Screenshot (365)_LI](https://user-images.githubusercontent.com/81338910/118314358-c17af900-b513-11eb-99a6-c2142fe4ecc5.jpg)
