### ISSUE TITLE
Dashboard problrm

### ISSUE THREAD

**Issue by Bishalpchhetri** [saman0i0/Portfolio-Management-System#16]
![185482298_473350913916576_8509033071379094132_n](https://user-images.githubusercontent.com/82128769/118358251-b53b7e00-b59d-11eb-9bba-b8414f32c292.png)

**Comment by Bishalpchhetri** [comment]
![186498423_137727635043253_3050770201918979297_n](https://user-images.githubusercontent.com/82128769/118358285-d603d380-b59d-11eb-9f89-7502cbe81657.png)

on clicking dashboard the information are not shown and an error page comes up. please fix this bug.

**Comment by karuna502** [comment]
![image](https://user-images.githubusercontent.com/81338971/118391488-43723b80-b654-11eb-93fc-a41803172c4b.png)
It works now
