### ISSUE TITLE
add stock problem 

### ISSUE THREAD

**Issue by Bishalpchhetri** [saman0i0/Portfolio-Management-System#17]
![185611769_291178049212881_6207747529729598563_n](https://user-images.githubusercontent.com/82128769/118359589-eae36580-b5a3-11eb-8d9f-dd02c3f9f2d2.png)

![185462297_298772611722870_6479921722326432859_n](https://user-images.githubusercontent.com/82128769/118358952-cf2a9000-b5a0-11eb-9bd4-d225c4c5a1f8.png)

On clicking add traction  an error page is shown . please fix this

**Comment by urushaudas** [comment]
![viber_image_2021-05-16_11-55-09](https://user-images.githubusercontent.com/81338910/118389665-9fd05d80-b64a-11eb-9f47-611242357e22.jpg)
![viber_image_2021-05-16_11-56-51](https://user-images.githubusercontent.com/81338910/118389670-a2cb4e00-b64a-11eb-8a93-5bc7c5868055.jpg)
The page is already fixed.
