### ISSUE TITLE
Logout system

### ISSUE THREAD

**Issue by Bishalpchhetri** [saman0i0/Portfolio-Management-System#18]
![186472359_2910253235886120_686969125847497459_n](https://user-images.githubusercontent.com/82128769/118359038-39dbcb80-b5a1-11eb-961d-c8ed1fccc135.png)

logout wasn't working accurately as it was taking long time to load please mantain this.

**Comment by karuna502** [comment]
I already solve this issue before you mentioned  and it working as well
![image](https://user-images.githubusercontent.com/81338971/118359438-33e6ea00-b5a3-11eb-970f-601c52d46f7a.png)
