### ISSUE TITLE
User registration page development.

### ISSUE THREAD

**Issue by saman0i0** [saman0i0/Portfolio-Management-System#2]

**Comment by karuna502** [comment]
![image](https://user-images.githubusercontent.com/81338971/118350745-29fbc180-b578-11eb-90a7-3f46b45e9c0e.png)
![image](https://user-images.githubusercontent.com/81338971/118350756-36801a00-b578-11eb-97ea-c4ed49925411.png)
 i changed entire log in and registration page of frontend and backend.
