### ISSUE TITLE
Backend Development of user registration page.

### ISSUE THREAD

**Issue by saman0i0** [saman0i0/Portfolio-Management-System#4]
Development of backend part user login page using Django.

**Comment by karuna502** [comment]
user login is already developed.
![login](https://user-images.githubusercontent.com/81338971/114830347-d4eb5500-9deb-11eb-9413-0ba5fdf67690.PNG)

**Comment by Bishalpchhetri** [comment]
please mantain margin, it has some errors

**Comment by karuna502** [comment]
This is a default admin login form .
