### ISSUE TITLE
Add stock page

### ISSUE THREAD

**Issue by Bishalpchhetri** [saman0i0/Portfolio-Management-System#6]
As a user I can keep track of the stocks that I own.

**Comment by urushaudas** [comment]
![viber_image_2021-05-16_11-50-48](https://user-images.githubusercontent.com/81338910/118389595-52ec8700-b64a-11eb-9984-47c4cba84930.jpg)
![viber_image_2021-05-16_11-55-09](https://user-images.githubusercontent.com/81338910/118389598-55e77780-b64a-11eb-916b-9a535a1c642c.jpg)
The user can add the stocks from the add stock page and it is stored in the database and it is displayed.
