### ISSUE TITLE
Backend part of dashboard

### ISSUE THREAD

**Issue by Bishalpchhetri** [saman0i0/Portfolio-Management-System#7]
As a user I want to see stock prices in my dashboard.

**Comment by Bishalpchhetri** [comment]
As a user I want to see net worth of my stocks.

**Comment by urushaudas** [comment]
![viber_image_2021-05-16_15-15-38](https://user-images.githubusercontent.com/81338910/118392497-c5b12e80-b659-11eb-939d-bbc805303665.jpg)
![viber_image_2021-05-16_15-18-15](https://user-images.githubusercontent.com/81338910/118392800-1ffebf00-b65b-11eb-8398-7b26bc48c014.jpg)
This is the dashboard of the system.
