### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by Bishalpchhetri** [saman0i0/Portfolio-Management-System#8]
![Screenshot (70)](https://user-images.githubusercontent.com/82128769/118139905-8d2a0e80-b427-11eb-8c7d-f2c62c3190af.png)

**Comment by Bishalpchhetri** [comment]
padding errors too...
![Screenshot (71)](https://user-images.githubusercontent.com/82128769/118139989-aa5edd00-b427-11eb-8ac1-11ec116ed2db.png)


please give better concern in margin and spelling

**Comment by karuna502** [comment]
Done

**Comment by karuna502** [comment]
![image](https://user-images.githubusercontent.com/81338971/118350535-02582980-b577-11eb-886e-6ff1fcc4ac53.png)
done
![image](https://user-images.githubusercontent.com/81338971/118350555-26b40600-b577-11eb-9c49-311fe89fbec2.png)
