### ISSUE TITLE
log in with social media

### ISSUE THREAD

**Issue by Bishalpchhetri** [saman0i0/Portfolio-Management-System#9]
please remove this fetaures because they are not functioning.
![Screenshot (72)](https://user-images.githubusercontent.com/82128769/118271653-4a2c7180-b4e1-11eb-8766-945fc9712f40.png)

**Comment by karuna502** [comment]
![image](https://user-images.githubusercontent.com/81338971/118351000-2ae12300-b579-11eb-834d-f1a0773e97ad.png)
done
